name: my_env
channels:
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - joblib
  - seaborn
  - matplotlib
  - pillow
  - pip:
    - opencv-python
    - torch==1.10.0
    - git+https://github.com/facebookresearch/detectron2.git
